---
- name: Install nginx using apt
  apt:
    pkg: nginx
    update_cache: yes

- name: Remove default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent

- set_fact: nginx_conf_dir="/etc/nginx/sites-enabled/"

- name: Create www-data user
  user:
    name: www-data
    system: yes
    create_home: no

- name: Copy nginx config
  template:
    src: templates/nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
  notify:
  - Restart nginx
