---
- hosts: all
  vars_files:
  - vars.yml

  gather_facts: false

  pre_tasks:
  - import_tasks: ../shared/pre-tasks.yml

  tasks:

  - import_tasks: ../shared/system-tasks.yml

  - import_tasks: ../shared/https-tasks.yml

  - name: Copy dnsmasq config
    copy:
      src: files/dnsmasq.conf
      dest: "/etc/dnsmasq.conf"
      group: deploy
    become: true
    notify:
    - restart dnsmasq

  - name: Ensure dnsmasq is running
    service: name=dnsmasq state=started enabled=yes
    become: true

  - import_tasks: ../shared/nginx-tasks.yml

  handlers:
  - import_tasks: ../shared/handlers.yml
