---
# apt packages
system_packages:
  - curl
  - git
  - make
  - python3.5
  - python3.5-venv
  - uwsgi
  - uwsgi-plugin-python3
  - sqlite3
  - npm
  - highlight

python3_executable: /usr/bin/python3.5

uwsgi_conf_dir: /etc/uwsgi/apps-enabled/
