---
# apt packages
system_packages:
  - curl
  - git
  - make
  - python3
  - python3-venv
  - uwsgi
  - uwsgi-plugin-python3
  - sqlite3
  - npm
  - highlight

python3_executable: /usr/bin/python3

uwsgi_executable: /usr/bin/uwsgi
uwsgi_conf_dir: /etc/uwsgi/apps-available/
uwsgi_python3_plugin: python3
