---
# the git repository URL
project_repo: https://github.com/periodo/periodo-server.git

# the version of the code to pull
project_repo_version: HEAD

# the root path to install to
install_root: "/srv/{{ server_name }}"

# the root path for www-visible documents
www_root: "/var/www/{{ server_name }}"

# the path to the sqlite db file
db_path: "{{ www_root }}/db.sqlite"

# the path to the nginx cache dir
cache_path: "/var/cache/{{ server_name }}"

# e.g. staging_perio_do not staging.perio.do
server_name_no_dots: "{{ server_name|replace('.', '_') }}"
