---
# apt packages
system_packages:
  - curl
  - git
  - make
  - python3
  - python3-venv
  - uwsgi
  - uwsgi-plugin-python3
  - sqlite3
  - npm
  - highlight

# python environment
python3_executable: /usr/bin/python3
uwsgi_executable: /usr/bin/uwsgi
uwsgi_conf_dir: /etc/uwsgi/apps-available/
uwsgi_python3_plugin: python3

# the git repository URL
project_repo: https://github.com/periodo/periodo-server.git

# the version of the code to pull
project_repo_version: master

# the root path to install to
install_root: "/srv/{{ server_name }}"

# the root path for www-visible documents
www_root: "/var/www/{{ server_name }}"

# the path to the temporary files directory
tmpdir_path: "{{ www_root }}/server_temp"

# the path to the sqlite db file
db_path: "{{ www_root }}/db.sqlite"

# the path to the csv query file
csv_query_path: "{{ www_root }}/periods-as-csv.rq"

# the path to the nginx cache dir
cache_path: "/var/cache/{{ server_name }}"

# e.g. staging_perio_do not staging.perio.do
server_name_no_dots: "{{ server_name|replace('.', '_') }}"

# admin ID and default permissions
admin_orcid: "https://orcid.org/0000-0002-5486-159X"
admin_permissions: "submit_patch,accept_patch,update_bag,update_graph"
