---
- name: Create directory for WWW files
  file:
    path: "{{ www_root }}"
    state: directory
    owner: www-data

- name: Fetch latest client tarball
  get_url:
    url: "https://{{ data_server_name }}/client-packages/periodo-client-{{ client_version }}.tgz"
    dest: "{{ www_root }}/periodo-client-{{ client_version }}.tgz"
    checksum: "sha256:https://{{ data_server_name }}/client-packages/periodo-client-{{ client_version }}.tgz.sha256"

- name: Extract latest client
  unarchive:
    remote_src: yes
    src: "{{ www_root }}/periodo-client-{{ client_version }}.tgz"
    dest: "{{ www_root }}"
    extra_opts:
    - --strip-components=1

- name: Remove tarball
  file:
    path: "{{ www_root }}/periodo-client-{{ client_version }}.tgz"
    state: absent

- name: Set PeriodO server URL in index.html
  replace:
    path: "{{ www_root }}/index.html"
    after: '<script type="text/javascript">'
    before: "</script>"
    regexp:
      "PERIODO_SERVER_URL = '[^']*'"
    replace:
      "PERIODO_SERVER_URL = 'https://{{ data_server_name }}/'"

- name: Set PeriodO proxy URL in index.html
  replace:
    path: "{{ www_root }}/index.html"
    after: '<script type="text/javascript">'
    before: "</script>"
    regexp:
      "PERIODO_PROXY_URL = '[^']*'"
    replace:
      "PERIODO_PROXY_URL = 'https://{{ corsproxy_server_name }}/'"

- name: Set PeriodO permalink URL in index.html
  replace:
    path: "{{ www_root }}/index.html"
    after: '<script type="text/javascript">'
    before: "</script>"
    regexp:
      "PERIODO_PERMALINK_URL = '[^']*'"
    replace:
      "PERIODO_PERMALINK_URL = 'http://n2t.net/ark:/99152/'"

- name: Copy nginx config
  template:
    src: templates/nginx.conf.j2
    dest: "{{ nginx_conf_dir }}{{ server_name }}.conf"
  notify:
  - Restart nginx

- name: Ensure nginx is running
  systemd:
    name: nginx.service
    enabled: yes
    state: started
