---
# the version of the client to deploy
client_version: latest

# the root path for www-visible documents
www_root: "/var/www/{{ server_name }}"

# associated server names
data_server_name: "{{ server_name|replace('client', 'data') }}"
corsproxy_server_name: "{{ server_name|replace('client', 'corsproxy') }}"
