---
- name: Install system packages
  apt:
    pkg: "{{ item }}"
    update-cache: yes
  with_items:
    - "{{ system_packages }}"

- name: Create deploy group
  group:
    name: deploy
    state: present

- name: Create sudo group
  group:
    name: sudo
    state: present

- name: Create www-data group
  group:
    name: www-data
    state: present

- name: Create directory for app
  file:
    path: "{{ install_root }}"
    state: directory
    group: deploy
    mode: u=rwx,g=rwx,o=rx,g+s

- name: Create directory for www files
  file:
    path: "{{ www_root }}"
    state: directory
    group: www-data
    mode: u=rwx,g=rwx,o=rx,g+s

- name: Make uwsgi apps-enabled writable by deploy group
  file:
    path: /etc/uwsgi/apps-enabled
    state: directory
    group: deploy
    mode: u=rwx,g=rwx,o=rx

- name: Make nginx sites-enabled writable by deploy group
  file:
    path: /etc/nginx/sites-enabled
    state: directory
    group: deploy
    mode: u=rwx,g=rwx,o=rx

- name: Remove default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent

# https stuff

- name: Clone/pull project repo
  git:
    repo: "{{ project_repo }}"
    dest: "{{ install_root }}"
  notify:
  - Restart uwsgi

- name: Install python packages
  pip:
    requirements: "{{ install_root }}/requirements.txt"
    virtualenv: "{{ install_root }}/venv"
    virtualenv_command: "/usr/bin/python3 -m venv"
  notify:
  - Restart uwsgi

- name: Copy secrets file
  template:
    src: files/secrets.py
    dest: "{{ install_root }}/periodo/secrets.py"
    group: deploy

- name: Upload PeriodO export file to be imported
  copy:
    src: "{{ import_file }}"
    dest: "{{ install_root }}/export.sql.gz"
    group: deploy
  when: import_file is defined

- name: Remove old export file
  file:
    state: absent
    path: "{{ install_root }}/export.sql.gz"
  when: import_url is defined

- name: Import PeriodO export file
  make:
    chdir: "{{ install_root }}"
    target: import
    params:
      IMPORT_URL: "{{ import_url | default('') }}"
      DB: "{{ db_path }}"
  when: (import_file is defined) or (import_url is defined)

- name: Create vocabulary file and update DB schema
  make:
    chdir: "{{ install_root }}"
    target: all
    params:
      DB: "{{ db_path }}"

- name: Make DB file writable by web server
  file:
    path: "{{ db_path }}"
    state: file
    mode: u=rwx,g=rwx,o=rx

- name: Upload initial data to be loaded
  copy:
    src: "{{ initial_data }}"
    dest: "{{ install_root }}/initial-data.json"
    group: deploy
  when: initial_data is defined

- name: Load initial data
  make:
    chdir: "{{ install_root }}"
    target: load_data
    params:
      DATA: "{{ install_root }}/initial-data.json"
  when: initial_data is defined

- name: Fetch latest client
  make:
    chdir: "{{ install_root }}"
    target: fetch_latest_client
  notify:
  - Restart uwsgi

- name: Remove old static files from WWW root
  file:
    path: "{{ www_root }}/static"
    state: absent

- name: Move new static files to WWW root
  command: mv "{{ install_root }}/periodo/static" "{{ www_root }}"
  args:
    removes: "{{ install_root }}/periodo/static"

- name: Copy uwsgi config
  template:
    src: templates/uwsgi.ini.j2
    dest: "/etc/uwsgi/apps-enabled/{{ server_name }}.ini"
    group: deploy
  notify:
  - Restart uwsgi

- name: Purge nginx cache
  file:
    state: absent
    path: "{{ cache_path }}"
  notify:
  - Restart nginx

- name: Copy nginx config
  template:
    src: templates/nginx.conf.j2
    dest: "/etc/nginx/sites-enabled/{{ server_name }}.conf"
    group: deploy
  notify:
  - Restart nginx

- name: Ensure uwsgi is running
  systemd:
    name: uwsgi
    enabled: yes
    state: started

- name: Ensure nginx is running
  systemd:
    name: nginx
    enabled: yes
    state: started
