---
- name: Copy dnsmasq config
  copy:
    src: files/dnsmasq.conf
    dest: "/etc/dnsmasq.conf"
    group: deploy
  notify:
  - Restart dnsmasq

- name: Ensure dnsmasq is running
  systemd:
    name: dnsmasq
    enabled: yes
    state: started

- name: Copy nginx config
  template:
    src: templates/nginx.conf.j2
    dest: "/etc/nginx/sites-enabled/{{ server_name }}.conf"
    group: deploy
  notify:
  - Restart nginx

- name: Ensure nginx is running
  systemd:
    name: nginx
    enabled: yes
    state: started

