---
# dnsmasq is a small name server used by nginx to resolve names of
# upstream servers into addresses. See:
# http://nginx.org/en/docs/http/ngx_http_core_module.html#resolver
- name: Install dnsmasq
  package:
    name: dnsmasq
    state: present

- name: Copy dnsmasq config
  copy:
    src: files/dnsmasq.conf
    dest: "/etc/dnsmasq.conf"
  notify:
  - Restart dnsmasq

- name: Ensure dnsmasq is running
  systemd:
    name: dnsmasq
    enabled: yes
    state: started

- name: Copy nginx config
  template:
    src: templates/nginx.conf.j2
    dest: "{{ nginx_conf_dir }}{{ server_name }}.conf"
  notify:
  - Restart nginx

- name: Ensure nginx is running
  systemd:
    name: nginx.service
    enabled: yes
    state: started

