---
- name: Add adoptopenjdk repository into apt sources list
  apt_repository:
    repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ focal main
    filename: adoptopenjdk
    state: present

- name: Install JRE using apt
  apt:
    name: "{{ jre }}"

- name: Set java alternative
  command: "update-alternatives --set java /usr/lib/jvm/{{ jre }}-amd64/bin/java"

- name: Download distribution tarball
  get_url:
    url: "http://archive.apache.org/dist/jena/binaries/apache-jena-{{ version }}.tar.gz"
    checksum: "{{ checksum }}"
    dest: "/opt/apache-jena-{{ version }}.tar.gz"

- name: Unarchive tarball
  unarchive:
    src: "/opt/apache-jena-{{ version }}.tar.gz"
    dest: /opt
    remote_src: yes

- name: Verify riot command exists
  file:
    path: "/opt/apache-jena-{{ version }}/bin/riot"
    state: file

- set_fact: riot_path="/opt/apache-jena-{{ version }}/bin/riot"

- name: Verify arq command exists
  file:
    path: "/opt/apache-jena-{{ version }}/bin/arq"
    state: file

- set_fact: arq_path="/opt/apache-jena-{{ version }}/bin/arq"

