---
- name: Install JRE using apt
  apt:
    name: default-jre

- name: Download distribution tarball
  get_url:
    url: http://mirrors.ibiblio.org/apache/jena/binaries/apache-jena-{{ version }}.tar.gz
    checksum: sha512:d1eba835acd0d15f959dd403918e17bc7e44312d3788640ab6a0d3453b22105f40a2c5feea675137d2773db74e4ca15dd018ff16d8576e01fdceba81e36f04fa
    dest: /opt/apache-jena-{{ version }}.tar.gz

- name: Unarchive tarball
  unarchive:
    src: /opt/apache-jena-{{ version }}.tar.gz
    dest: /opt
    remote_src: yes

- name: Verify riot command exists
  file:
    path: /opt/apache-jena-{{ version }}/bin/riot
    state: file

- set_fact: riot_path="/opt/apache-jena-{{ version }}/bin/riot"

