---
- name: Install JRE using apt
  apt:
    name: default-jre

- name: Download distribution tarball
  get_url:
    url: "http://mirrors.ibiblio.org/apache/jena/binaries/apache-jena-{{ version }}.tar.gz"
    checksum: "{{ checksum }}"
    dest: "/opt/apache-jena-{{ version }}.tar.gz"

- name: Unarchive tarball
  unarchive:
    src: "/opt/apache-jena-{{ version }}.tar.gz"
    dest: /opt
    remote_src: yes

- name: Verify riot command exists
  file:
    path: "/opt/apache-jena-{{ version }}/bin/riot"
    state: file

- set_fact: riot_path="/opt/apache-jena-{{ version }}/bin/riot"

