---
- name: Install apt transport for downloading via https
  apt:
    name: apt-transport-https

- name: Download the Adoptium GPG key
  get_url:
    url: "https://packages.adoptium.net/artifactory/api/gpg/key/public"
    dest: "{{ key_path }}"
    mode: "644"

- name: Add Adoptium repository into apt sources list
  apt_repository:
    repo: "deb [signed-by={{ key_path }}] https://packages.adoptium.net/artifactory/deb {{ ubuntu_version }} main"
    filename: adoptium
    state: present

- name: Install JDK using apt
  apt:
    name: "{{ jdk }}"

- name: Set java alternative
  command: "update-alternatives --set java /usr/lib/jvm/{{ jdk }}-amd64/bin/java"

- name: Download distribution tarball
  get_url:
    url: "http://archive.apache.org/dist/jena/binaries/apache-jena-{{ version }}.tar.gz"
    checksum: "{{ checksum }}"
    dest: "/opt/apache-jena-{{ version }}.tar.gz"
    mode: "666"

- name: Unarchive tarball
  unarchive:
    src: "/opt/apache-jena-{{ version }}.tar.gz"
    dest: /opt
    remote_src: yes

- name: Verify riot command exists
  file:
    path: "/opt/apache-jena-{{ version }}/bin/riot"
    state: file

- set_fact: riot_path="/opt/apache-jena-{{ version }}/bin/riot"

- name: Verify arq command exists
  file:
    path: "/opt/apache-jena-{{ version }}/bin/arq"
    state: file

- set_fact: arq_path="/opt/apache-jena-{{ version }}/bin/arq"

