---
- name: Copy SSL certificate
  copy:
    src: lib.utexas.edu.pem
    dest: "{{ https_chain }}"
    owner: root
    group: root
    mode: 0644
  register: ssl_cert

- name: Copy SSL key
  copy:
    src: lib.utexas.edu.key
    dest: "{{ https_key }}"
    owner: root
    group: root
    mode: 0640
  register: ssl_key

- name: Create Diffie–Hellman parameters
  shell: >
    openssl dhparam -dsaparam -out {{ https_dhparams }} {{ rsa_key_size }}
  when: ssl_cert is changed or ssl_key is changed
